### ISSUE TITLE
Custom Enchants not being added

### ISSUE THREAD

**Issue by EpicPinkCreeper** [poggit-orphanage/AdvancedKits#12]
The custom enchants work normally by itself, but it wont be added to the items in the kit like it used to.

**Comment by Awzaw** [comment]
Please try again with the latest dev build

**Comment by Awzaw** [comment]
And make sure you don't set enchantments to higher than their maximum as defined in PiggyCustomEnchants

**Comment by Awzaw** [comment]
This repo will be deleted soon, please see the original at https://github.com/luca28pet/AdvancedKits
