### ISSUE TITLE
Error every time advanced kits tries to start up

### ISSUE THREAD

**Issue by Zedstar16** [poggit-orphanage/AdvancedKits#14]
I get this in the server console:

30.03 15:35:27 [Server] Server thread/INFO Enabling AdvancedKits v5.1.1
30.03 15:35:27 [Server] Server thread/CRITICAL ErrorException: "Invalid argument supplied for foreach()" (EXCEPTION) in "AdvancedKits_dev-23.phar/src/AdvancedKits/Main" at line 96
30.03 15:35:27 [Server] Server thread/DEBUG #0 AdvancedKits_dev-23.phar/src/AdvancedKits/Main(96): pocketmine\error_handler(integer 2, string Invalid argument supplied for foreach(), string phar:///plugins/AdvancedKits_dev-23.phar/src/AdvancedKits/Main.php, integer 96, array Array())
30.03 15:35:27 [Server] Server thread/DEBUG #1 AdvancedKits_dev-23.phar/src/AdvancedKits/Main(89): AdvancedKits\Main->fixConfig(string noobkit)
30.03 15:35:27 [Server] Server thread/DEBUG #2 AdvancedKits_dev-23.phar/src/AdvancedKits/Main(33): AdvancedKits\Main->loadKits()
30.03 15:35:27 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/PluginBase(90): AdvancedKits\Main->onEnable()
30.03 15:35:27 [Server] Server thread/DEBUG #4 src/pocketmine/plugin/PharPluginLoader(122): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
30.03 15:35:27 [Server] Server thread/DEBUG #5 src/pocketmine/plugin/PluginManager(573): pocketmine\plugin\PharPluginLoader->enablePlugin(AdvancedKits\Main object)
30.03 15:35:27 [Server] Server thread/DEBUG #6 src/pocketmine/Server(1919): pocketmine\plugin\PluginManager->enablePlugin(AdvancedKits\Main object)
30.03 15:35:27 [Server] Server thread/DEBUG #7 src/pocketmine/Server(1905): pocketmine\Server->enablePlugin(AdvancedKits\Main object)
30.03 15:35:27 [Server] Server thread/DEBUG #8 src/pocketmine/Server(1699): pocketmine\Server->enablePlugins(integer 1)
30.03 15:35:27 [Server] Server thread/DEBUG #9 src/pocketmine/PocketMine(305): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
30.03 15:35:27 [Server] Server thread/INFO Disabling AdvancedKits v5.1.1

**Comment by Awzaw** [comment]
This repo will be deleted soon, please see the original at https://github.com/luca28pet/AdvancedKits
