### ISSUE TITLE
Original plugin update

### ISSUE THREAD

**Issue by luca28pet** [poggit-orphanage/AdvancedKits#16]
I updated AdvancedKits some days ago to support the latest API (alpha 12) so it is no longer abandoned.
Can you remove your version from poggit?

**Comment by SOF3** [comment]
Would you like to have everything in this fork repo entirely deleted, or would you like to make Poggit internally transfer the ownership of this project/release to yours? We can provide the following options:

- Reassociate https://poggit.pmmp.io/p/AdvancedKits to your own Poggit project. This allows retaining the past reviews, downloads, etc. This is equivalent to transferring the ownership of this release to you.
- Delete this fork and all associated Poggit builds and releases entirely.

**Comment by luca28pet** [comment]
I would like to delete this fork and its releases on poggit if possible

**Comment by SOF3** [comment]
I just realized there isn't a Poggit release for this plugin

I'll wait for @Awzaw's comment before deleting.

**Comment by Awzaw** [comment]
Sorry I missed this... @luca28pet great news :-) @sof3 if you didn't already delete, be my guest
