### ISSUE TITLE
CustomEnchants don't work

### ISSUE THREAD

**Issue by Atm85** [poggit-orphanage/AdvancedKits#17]
`[Server thread/CRITICAL]: Unhandled exception executing command 'kit starter' in kit: Object of class PiggyCustomEnchants\CustomEnchants\CustomEnchants could not be converted to string
[Server thread/CRITICAL]: ErrorException: "Object of class PiggyCustomEnchants\CustomEnchants\CustomEnchants could not be converted to string" (EXCEPTION) in "_PiggyCustomEnchants/src/PiggyCustomEnchants/Main" at line 463`

im using advanced kits latest from this repo and latest release version of custom enchants

**Comment by Awzaw** [comment]
This repo will be deleted soon, please see the original at https://github.com/luca28pet/AdvancedKits
